/*

*/

--VERIFICA SE A PROCEDURE A SER REMOVIDA POSSUI DEPENDENCIAS
EXECUTE deptree_fill('PROCEDURE','USER_DEV','INCLUIR_CLIENTE');
SELECT NESTED_LEVEL,SCHEMA,TYPE,NAME FROM deptree
ORDER BY SEQ#;

--COMANDO PARA DROPAR A PROCEDURE/FUNCTION
DROP PROCEDURE INCLUIR_CLIENTE;
DROP PROCEDURE EXCLUIR_CLIENTE;
DROP PROCEDURE ATUALIZAR_CLI_SEG_MERCADO;
DROP PROCEDURE ATUALIZAR_FATURAMENTO_PREVISTO;

DROP PROCEDURE FORMAT_CNPJ;

DROP FUNCTION OBTER_CATEGORIA_CLIENTE;
DROP FUNCTION VERIFICA_SEGMENTO_MERCADO;


