/*
    PRIVILEGIO DE ACESSO PUBLICO PARA O PACOTE EXCEPTION
*/

-- LOGIN COM user_dev PARA DAR O PREVILEGIO PARA O user_app;
GRANT SELECT,INSERT ON SEGMERCADO TO user_app;

-- CRIANDO SINONIMO ÁRA TABELA DE SEGMERCADO
CREATE OR REPLACE PUBLIC SYNONYM SEGMERCADO FOR user_dev.Segmercado;

-- DANDO PERMISSÃO PUBLICA PARA O PACOTE, QUALQUER PESSOA PODE CONSUMIR
GRANT EXECUTE ON EXCEPTION_PAC TO PUBLIC;

-- ASSICIANDO SINONIMO AO PACOTE
CREATE OR REPLACE PUBLIC SYNONYM EXCEPTION_PAC FOR user_dev.EXCEPTION_PAC;

--************************ CRIANDO PROCEDURE *********************************
CREATE OR REPLACE PROCEDURE APP_INCLUIR_SEGMENTO
(P_ID SEGMERCADO.ID%TYPE, P_DESCRICAO SEGMERCADO.DESCRICAO%TYPE)
IS
BEGIN
    INSERT INTO SEGMERCADO(ID,DESCRICAO)
    VALUES(P_ID,P_DESCRICAO);
    
    EXCEPTION
    WHEN EXCEPTION_PAC.e_null then
     raise_application_error(-20015,'Campo do segmento com preenchimento obrigatorio');
    WHEN OTHERS THEN
     raise_application_error(-20010,'ERRO GENERICO' || SQLERRM());
END;

EXECUTE APP_INCLUIR_SEGMENTO(NULL,'EGGEG');


