
--Percent Type
/*
    [PERCENT TYPE]
     - É UMA FORMA DE NÃO FIXAR O VALOR DIRETO NA DECLARAÇÃO DA VARIAVEL,
     COM "PERCENT TYPE" ESTAMOS QUERENDO DIZER QUE TAL VARIAVEL IRÁ CONTER
     O MESMO TIPO DA COLUNA DA TABELA.
     
     ESTOU INFORMANDO QUE O TIPO DA VARIAVEL "V_ID" É DO MESMO TIPO DA COLUNA 
     "ID" DA TABELA "SEG_MERCADO"
     V_ID SEG_MERCADO.ID%TYPE := 1;
*/

DECLARE
    -- SINTAXE 
    V_ID SEG_MERCADO.ID%TYPE := 2;
    V_DESCRICAO SEG_MERCADO.DESCRICAO%TYPE  := 'VAREJO2';    
BEGIN

    INSERT INTO SEG_MERCADO (ID,DESCRICAO) VALUES (V_ID,V_DESCRICAO);
    COMMIT;
END;


SELECT*FROM SEG_MERCADO;