--VARIOS COMANDOS EM BLOCO;

DECLARE    
    V_ID SEG_MERCADO.ID%TYPE := 3;
    V_DESCRICAO SEG_MERCADO.DESCRICAO%TYPE  := 'AtacadISTA ';    
BEGIN
    
    UPDATE SEG_MERCADO SET DESCRICAO = UPPER(V_DESCRICAO) WHERE ID = V_ID;
    
    V_ID:=2;
    V_DESCRICAO := 'VArejista';
    UPDATE SEG_MERCADO SET DESCRICAO = UPPER(V_DESCRICAO) WHERE ID = V_ID;
    
    COMMIT;    
    
END;

SELECT*FROM SEG_MERCADO;
