-- REMOVENDO REGISTROS


DECLARE

    V_ID SEG_MERCADO.ID%TYPE := 4;
    V_DESCRICAO SEG_MERCADO.DESCRICAO%TYPE := 'ESPOSTISTAS';

BEGIN 
    
    INSERT INTO SEG_MERCADO (ID,DESCRICAO) VALUES (V_ID,UPPER(V_DESCRICAO));
    COMMIT;
END;

SELECT*FROM SEG_MERCADO;

--REMOVENDO REGISTROS
DECLARE

    V_ID SEG_MERCADO.ID%TYPE := 4;

BEGIN 
    
    DELETE FROM SEG_MERCADO WHERE ID = V_ID;
    COMMIT;
END;


