--


-- manutenção da procedure/ FORMA DE ATUALIZAR UMA PROCEDURE
CREATE OR REPLACE PROCEDURE INCLUIR_SEG_MERCADO
(P_ID IN SEG_MERCADO.ID%TYPE, P_DESCRICAO SEG_MERCADO.DESCRICAO%TYPE)
IS
BEGIN 
 INSERT INTO SEG_MERCADO (ID,DESCRICAO) VALUES (P_ID,UPPER(P_DESCRICAO));
    COMMIT;
END;

