
--Função no oracle
-- Montando comando pl/sql
SET SERVEROUTPUT ON;
DECLARE
    V_ID SEG_MERCADO.ID%TYPE :=6;
    V_DESCRICAO SEG_MERCADO.DESCRICAO%TYPE;
BEGIN 
    -- FORMA DE ATRIBUIR O VALOR DE UM SELECT A UMA VARIAVEL
    -- SINTAXE: "INTO 'Variavel' "
    SELECT DESCRICAO INTO V_DESCRICAO FROM SEG_MERCADO WHERE ID = V_ID;
    DBMS_OUTPUT.put_line(V_DESCRICAO);
END;

-- Criando Função - SINTAXE
CREATE OR REPLACE FUNCTION Obter_Descricao_Seg_Mercado
    (P_ID SEG_MERCADO.ID%type)
    RETURN SEG_MERCADO.DESCRICAO%TYPE -- RETORNO DA FUNÇÃO
IS
    V_DESCRICAO_RESULT SEG_MERCADO.DESCRICAO%TYPE;
BEGIN    
    SELECT DESCRICAO INTO V_DESCRICAO_RESULT FROM SEG_MERCADO WHERE ID = P_ID;
    
    RETURN V_DESCRICAO_RESULT;
END;


--****************************EXECULTANDO FUNÇÃO*******************************

-- FORMA DE EXECULTAR UMA FUNÇÃO DENTRO DO SQL_DEVELOPMENT
VARIABLE G_DESCRICAO VARCHAR2(100);
EXECUTE :G_DESCRICAO := Obter_Descricao_Seg_Mercado(6);
PRINT G_DESCRICAO;

-- FORMA DE EXECULTAR UMA FUNÇÃO UTILIZANDO O PL/SQL
SET SERVEROUTPUT ON;
DECLARE
    V_DESCRICAO SEG_MERCADO.DESCRICAO%TYPE;
BEGIN
    V_DESCRICAO := Obter_Descricao_Seg_Mercado(6);    
    dbms_output.put_line('A Descrição do segmento de mercado é ' || v_descricao);
END;


 