
--RETORNANDO VALORES COM UMA PROCEDURE
/*
    PARAMETROS "IN", "OUT".
    É SEMELHANTE COM O "OUT", DO C#, A VARIAVEL É PASSADA COMO REFERENCIA,
    OU SEJA TUDO QUE ACONTECER COM A VARIAVEL DENTRO DA ROTINA SERÁ RETORNADO 
    POR MEIO DELA MESMO.
*/

CREATE OR REPLACE PROCEDURE FORMAT_CNPJ
    (P_CNPJ IN CLIENTE.CNPJ%TYPE, P_CNPJ_RESULT OUT CLIENTE.CNPJ%TYPE)
IS
BEGIN
    P_CNPJ_RESULT := regexp_replace(LPAD(P_CNPJ, 11),'([0-9]{3})([0-9]{3})([0-9]{3})','\1.\2.\3-');
END;

-- Testando procedure com retorno
VARIABLE G_CNPJ VARCHAR2(20);
VARIABLE G_CNPJ_SAIDA VARCHAR2(20);

EXECUTE :G_CNPJ := '42813729892';

EXECUTE FORMAT_CNPJ(:G_CNPJ,:G_CNPJ_SAIDA);
PRINT :G_CNPJ;
PRINT :G_CNPJ_SAIDA;


