-- O mesmo parametro da procedure pode ser de entrada e saida

CREATE OR REPLACE PROCEDURE FORMAT_CNPJ
    (P_CNPJ IN OUT CLIENTE.CNPJ%TYPE)
IS
BEGIN
    P_CNPJ := regexp_replace(LPAD(P_CNPJ, 11),'([0-9]{3})([0-9]{3})([0-9]{3})','\1.\2.\3-');
END;
COMMIT;


-- Manipulando Tabelas
CREATE OR REPLACE PROCEDURE INCLUIR_CLIENTE
(P_ID CLIENTE.ID%TYPE,
P_RAZAO_SOCIAL IN CLIENTE.RAZAO_SOCIAL%TYPE,
P_CNPJ IN CLIENTE.CNPJ%TYPE,
P_SEGMERCADO_ID IN CLIENTE.SEQMERCADO_ID%TYPE,
P_FATURAMENTO_PREVISTO IN CLIENTE.FATURAMENTO_PREVISTO%TYPE)
IS
    v_CATEGORIA CLIENTE.CATEGORIA%TYPE;
    v_CNPJ CLIENTE.CNPJ%TYPE := P_CNPJ;
BEGIN
    --UTILIZANDO FUNÇÃO DENTRO DA PROCEDURE
    v_CATEGORIA := categoria_cliente(P_FATURAMENTO_PREVISTO);    
    FORMAT_CNPJ(v_CNPJ);
    
    INSERT INTO cliente (id,razao_social,cnpj,seqmercado_id,data_inclusao,faturamento_previsto,categoria)
              VALUES (P_ID,P_RAZAO_SOCIAL,v_CNPJ,P_SEGMERCADO_ID,SYSDATE,P_FATURAMENTO_PREVISTO,v_CATEGORIA);
    COMMIT;
END;


EXEC incluir_cliente(9,'SUPERMERCADO IJK','42813723655',2,9000);
SELECT*FROM CLIENTE;

COMMIT;