-- Criação de procedure para atualizar tabela

CREATE OR REPLACE PROCEDURE ATUALIZAR_CLI_SEG_MERCADO
(P_ID IN CLIENTE.ID%TYPE, P_SEGMERCADO_ID IN CLIENTE.SEQMERCADO_ID%TYPE)
IS
BEGIN
    UPDATE CLIENTE SET SEQMERCADO_ID = P_SEGMERCADO_ID 
    WHERE ID = P_ID;
    
    COMMIT;
END;

SELECT*FROM CLIENTE;

EXECUTE atualizar_cli_seg_mercado(5,7);

SELECT*FROM seg_mercado;
